[project]
name = "va-credentials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastexcel>=0.13.0",
    "marimo>=0.12.8",
    "polars>=1.27.1",
]
